title: hello
email: wesleyem@pm.me
description: >
  Welcome to my blog that delves into diverse topics, including self-hosted applications,
  software development, application security, cybersecurity, networking, privacy,
  containers, and other abstractions that pique my interest.
author: Wesley Montserrat
baseurl: ""
url: "https://hello.wesleyem.com"

# Social Profiles
twitter_username: spo0f_
github_username: wesleyem
facebook_username:
instagram_username:
linkedin_username: wesleymontserrat

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
